/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_servlet_TechLib */

#ifndef _Included_main_java_servlet_TechLib
#define _Included_main_java_servlet_TechLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_servlet_TechLib
 * Method:    techHELib
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_java_servlet_TechLib_techHELib
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
